apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  template:
    spec:
      # Create /opt/kata directory that isn't noexec
      # initContainers:
      # - name: init-opt-kata
      #   image: busybox
      #   command: ["/bin/sh", "-c"]
      #   args:
      #   - |
      #     mkdir -p /host/opt/kata
      #     mount --bind /home/kubernetes/kata /host/opt/kata
      #   securityContext:
      #     privileged: true
      #   volumeMounts:
      #   - name: host
      #     mountPath: /host

      containers:
      - name: kube-kata
        env:
        - name: DEBUG
          value: "true"
        - name: INSTALLATION_PREFIX
          value: /var/lib/google/kata


      volumes:
      # Path to containerd config.toml file
      - name: containerd-conf
        hostPath:
          path: /etc/containerd

      # We can't use /opt/kata on Container-Optimized OS
      - name: kata-artifacts
        hostPath:
          path: /var/lib/google/kata
          type: DirectoryOrCreate
